#!name=2345网址导航
#!desc=某些APP要清除缓存或者重新安装拦截广告才会生效！
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Rule]
DOMAIN-SUFFIX,dl.2345.com,REJECT
DOMAIN-SUFFIX,download.2345.com,REJECT
DOMAIN-SUFFIX,ggcode.2345.com,REJECT
DOMAIN-SUFFIX,houtai.2345.com,REJECT
DOMAIN-SUFFIX,jifen.2345.com,REJECT
DOMAIN-SUFFIX,minipage.2345.com,REJECT
DOMAIN-SUFFIX,wan.2345.com,REJECT
DOMAIN-SUFFIX,zhushou.2345.com,REJECT
DOMAIN-SUFFIX,tg.jifen.2345.com,REJECT
DOMAIN-SUFFIX,update.minipage.2345.com,REJECT
DOMAIN-SUFFIX,g.wan.2345.com,REJECT
