#!name=Braze
#!desc=某些APP要清除缓存或者重新安装拦截广告才会生效！
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Rule]
DOMAIN-SUFFIX,iad.appboy.com,REJECT
DOMAIN-SUFFIX,iad-03.appboy.com,REJECT
DOMAIN-SUFFIX,iad-01.braze.com,REJECT
DOMAIN-SUFFIX,iad-02.braze.com,REJECT
DOMAIN-SUFFIX,iad-03.braze.com,REJECT
DOMAIN-SUFFIX,iad-04.braze.com,REJECT
DOMAIN-SUFFIX,iad-05.braze.com,REJECT
DOMAIN-SUFFIX,iad-06.braze.com,REJECT
DOMAIN-SUFFIX,iad-08.braze.com,REJECT
