#!name=民生银行
#!desc=某些APP要清除缓存或者重新安装拦截广告才会生效！
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Rule]
DOMAIN-KEYWORD,cm-10-134.getui.com,REJECT
DOMAIN-KEYWORD,sdk.open.talk.getui.com,REJECT
DOMAIN-KEYWORD,cm-10-35.getui.com,REJECT
DOMAIN-KEYWORD,c-hzgt2.getui.com,REJECT
DOMAIN-SUFFIX,sdk.open.talk.igexin.com,REJECT

[Map Local]
^https?:\/\/www\.cmbc\.com\.cn\/m\/image\/loadingpage\/ data-type=text data=" " status-code=200
^https?:\/\/www\.cmbc\.com\.cn\/m\/image\/banner\/.*.png data-type=text data=" " status-code=200

[MITM]
hostname = %APPEND% www.cmbc.com.cn, rs.creditcard.cmbc.com.cn
