#!name=中国电信
#!desc=某些APP要清除缓存或者重新安装拦截广告才会生效！
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Rule]
DOMAIN,ad.21cn.com,REJECT
DOMAIN,ad.k.21cn.com,REJECT
DOMAIN,admarket.21cn.com,REJECT
DOMAIN,adshows.21cn.com,REJECT
IP-CIDR,122.229.8.47/32,REJECT,no-resolve
IP-CIDR,122.229.29.89/32,REJECT,no-resolve

[URL Rewrite]
^https?:\/\/cloud\.189\.cn\/include\/splash\/ - reject

[Map Local]
^https?:\/\/zt-app\.go189\.cn\/zt-app\/welcome\/.*?Animation data-type=tiny-gif status-code=200

[MITM]
hostname = %APPEND% cloud.189.cn, zt-app.go189.cn
