#!name=CSDN
#!desc=某些APP要清除缓存或者重新安装拦截广告才会生效！
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Rule]
DOMAIN-SUFFIX,ad.csdn.net,REJECT
DOMAIN-SUFFIX,counter.csdn.net,REJECT
DOMAIN-SUFFIX,dc.csdn.net,REJECT
DOMAIN-SUFFIX,dc2.csdn.net,REJECT
DOMAIN-SUFFIX,medal.blog.csdn.net,REJECT

[URL Rewrite]
^https?:\/\/app-gw\.csdn\.net\/silkroad-api\/api\/v\d\/assemble\/list\/pub\/channel\/app_open_screen_ad - reject
^https?:\/\/app-gw\.csdn\.net\/abtesting\/v2\/getList? - reject
^https?:\/\/gw\.csdn\.net\/cms-app\/v\d+\/home_page\/open_advertisement - reject

[MITM]
hostname = %APPEND% app-gw.csdn.net, gw.csdn.net
