#!name=携程
#!desc=某些APP要清除缓存或者重新安装拦截广告才会生效！
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[URL Rewrite]
^https?:\/\/ma-adx\.ctrip\.com\/_ma\.gif - reject
^https?:\/\/mbd\.baidu\.com\/newspage\/api\/getmobads\?page\=landingshare - reject

[Map Local]
^https?:\/\/m\.ctrip\.com\/restapi\/soa2\/[0-9]{5}\/json\/getTimeZoneServerIpList\?__gw_os=IOS data-type=text data=" " status-code=200
^https?:\/\/m\.ctrip\.com\/restapi\/soa2\/13916\/json\/tripAds data-type=text data=" " status-code=200

[MITM]
hostname = %APPEND% m.ctrip.com, ma-adx.ctrip.com, mbd.baidu.com
