#!name=当当阅读
#!desc=某些APP要清除缓存或者重新安装拦截广告才会生效！
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[URL Rewrite]
^https?:\/\/e\.dangdang\.com\/media\/api.+\?action=getDeviceStartPage - reject
^https?:\/\/e\.dangdang\.com\/.+?getDeviceStartPage - reject
^https?:\/\/api\.dangdang\.com\/mapi\d\/mobile\/init - reject
^https?:\/\/mapi\.dangdang\.com\/index\.php\?action=init - reject

[MITM]
hostname = %APPEND% e.dangdang.com, api.dangdang.com, mapi.dangdang.com
