#!name=嘀嗒出行
#!desc=某些APP要清除缓存或者重新安装拦截广告才会生效！
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[URL Rewrite]
^https?:\/\/capis(-\d)?\.didapinche\.com\/adbase - reject
^https?:\/\/capis(-\d)?\.didapinche\.com\/ad\/ - reject

[Map Local]
^https?:\/\/adx-cn\.anythinktech\.com\/bid data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https?:\/\/capis(-?\w*)?\.didapinche\.com\/publish\/api\/upgrade data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https?:\/\/www\.didapinche\.com\/app\/adstat\/ data-type=text data=" " status-code=200

[MITM]
hostname = %APPEND% capis*.didapinche.com, adx-cn.anythinktech.com, www.didapinche.com
