#!name=滴滴青桔
#!desc=某些APP要清除缓存或者重新安装拦截广告才会生效！
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Rule]
IP-CIDR,203.107.1.1/24,REJECT,no-resolve

[Map Local]
^https?:\/\/pt-starimg\.didistatic\.com\/static\/starimg\/node\/.*.(jpg|png|gif) data-type=text data=" " status-code=200
^https?:\/\/omgup[0-9]{1}\.xiaojukeji\.com\/api data-type=text data=" " status-code=200

[MITM]
hostname = %APPEND% pt-starimg.didistatic.com, omgup*.xiaojukeji.com
