#!name=低端影视
#!desc=某些APP要清除缓存或者重新安装拦截广告才会生效！
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Map Local]
^https?:\/\/img\.ddrk\.me\/ad190824 data-type=tiny-gif status-code=200
^https?:\/\/img\.ddrk\.me\/cover\.png data-type=tiny-gif status-code=200
^https?:\/\/ddrk\.me\/image\/logo_footer\.png data-type=tiny-gif status-code=200
^https?:\/\/ddrk\.me\/wp-content\/plugins\/advanced-floating-content-lite\/public\/images\/close\.png data-type=tiny-gif status-code=200

[MITM]
hostname = %APPEND% img.ddrk.me, ddrk.me
