#!name=盯盯拍
#!desc=某些APP要清除缓存或者重新安装拦截广告才会生效！
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[URL Rewrite]
^https?:\/\/.*\.pglstatp-toutiao\.com\/.*ad.* - reject
^https?:\/\/api\.htp\.ad-scope\.com\.cn.* - reject
^https?:\/\/appgw\.ddpai\.com.*\/ad\/list.* - reject
^https?:\/\/init\.sms\.mob\.com\/.*sdk\/init.* - reject

[Map Local]
^https?:\/\/apphw\.ddpai\.com:\d+\/onroad\/api\/v\d\/\w+\/list data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[MITM]
hostname = %APPEND% *.pglstatp-toutiao.com, api.htp.ad-scope.com.cn, appgw.ddpai.com, init.sms.mob.com, apphw.ddpai.com
