#!name=东方财富
#!desc=某些APP要清除缓存或者重新安装拦截广告才会生效！
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Rule]
DOMAIN-SUFFIX,bduserlog.eastmoney.com,REJECT
DOMAIN-SUFFIX,js4.eastmoney.com,REJECT
DOMAIN-SUFFIX,same.eastmoney.com,REJECT

[URL Rewrite]
^https?:\/\/emdcadvertise\.eastmoney\.com\/infoService\/v\d - reject

[Map Local]
^https?:\/\/app\.ceair\.com\/customize\/security\/update data-type=text data=" " status-code=200
^https?:\/\/app\.ceair\.com\/customize\/main\/adScreen data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[MITM]
hostname = %APPEND% app.ceair.com
