#!name=豆瓣
#!desc=某些APP要清除缓存或者重新安装拦截广告才会生效！
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Rule]
DOMAIN-SUFFIX,erebor.douban.com,REJECT
DOMAIN-SUFFIX,ad.doubanio.com,REJECT

[URL Rewrite]
^https?:\/\/img\d\.doubanio\.com\/view\/dale-online\/dale_ad\/ - reject
^https?:\/\/frodo\.douban\.com\/api\/v2\/movie\/banner - reject
^https?:\/\/erebor\.douban\.com\/count\/\?ad= - reject

[Map Local]
^https?:\/\/api\.douban\.com\/v\d\/app_ads\/ data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https?:\/\/api\.douban\.com\/b.*\/common_ads\?.* data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[MITM]
hostname = %APPEND% api.douban.com
