#!name=艺龙旅行网
#!desc=某些APP要清除缓存或者重新安装拦截广告才会生效！
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[URL Rewrite]
^https?:\/\/webboot\.zhangyue\.com\/zycl\/api\/ad\/ - reject
^https?:\/\/saad\.ms\.zhangyue\.net\/ad - reject

[Map Local]
^https?:\/\/mobile-api2011\.elong\.com\/ad(?>v|gateway) data-type=text data=" " status-code=200

[MITM]
hostname = %APPEND% mobile-api2011.elong.com, webboot.zhangyue.com, saad.ms.zhangyue.net
