#!name=丰巢
#!desc=某些APP要清除缓存或者重新安装拦截广告才会生效！
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[URL Rewrite]
^https:\/\/dsp\.fcbox\.com\/adSearch\/get\? - reject
^https:\/\/external\.fcbox\.com\/wxgw\/post\/suggestion\/query - reject
^https:\/\/rtm\.fcbox\.com\/rtsWeb\/api\/resource\/ad\/queryAd - reject
^https?:\/\/consumer\.fcbox\.com\/v\d\/ad\/ - reject

[MITM]
hostname = %APPEND% external.fcbox.com, dsp.fcbox.com, consumer.fcbox.com, rtm.fcbox.com
