#!name=风行网
#!desc=某些APP要清除缓存或者重新安装拦截广告才会生效！
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Rule]
DOMAIN-SUFFIX,pb.funshion.net.cn,REJECT
DOMAIN-SUFFIX,ad.funshion.org.cn,REJECT
DOMAIN-SUFFIX,adk.funshion.com,REJECT
DOMAIN-SUFFIX,adm.funshion.com,REJECT
DOMAIN-SUFFIX,conf.funshion.com,REJECT
DOMAIN-SUFFIX,pub.funshion.com,REJECT
DOMAIN-SUFFIX,vas.funshion.com,REJECT
DOMAIN-SUFFIX,vs.funshion.com,REJECT
DOMAIN-SUFFIX,aa0.pub.funshion.com,REJECT
DOMAIN-SUFFIX,aa1.pub.funshion.com,REJECT
DOMAIN-SUFFIX,rt.funshion.net,REJECT
