#!name=Go.com
#!desc=某些APP要清除缓存或者重新安装拦截广告才会生效！
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Rule]
DOMAIN-SUFFIX,ad.go.com,REJECT
DOMAIN-SUFFIX,adimages.go.com,REJECT
DOMAIN-SUFFIX,ngads.go.com,REJECT
DOMAIN-SUFFIX,w88.go.com,REJECT
DOMAIN-SUFFIX,verdict.abc.go.com,REJECT
DOMAIN-SUFFIX,oascentral.abclocal.go.com,REJECT
DOMAIN-SUFFIX,dcapps.disney.go.com,REJECT
DOMAIN-SUFFIX,adsatt.espn.go.com,REJECT
DOMAIN-SUFFIX,seavideo-ak.espn.go.com,REJECT
