#!name=韩剧TV
#!desc=某些APP要清除缓存或者重新安装拦截广告才会生效！
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Rule]
DOMAIN,mi.gdt.qq.com,REJECT
DOMAIN,adsmind.ugdtimg.com,REJECT
DOMAIN,pgdt.ugdtimg.com,REJECT
DOMAIN,v2mi.gdt.qq.com,REJECT
DOMAIN,da.bridgeturbo.com,REJECT
DOMAIN,adx-os.bridgeturbo.com,REJECT
DOMAIN,adx-bj.anythinktech.com,REJECT
DOMAIN,mobads.baidu.com,REJECT

[URL Rewrite]
^https?:\/\/gfp\.veta\.naver\.com\/adcall\? - reject
^https?:\/\/api\.hanju\.koudaibaobao\.com\/api\/carp\/kp\? - reject

[MITM]
hostname = %APPEND% gfp.veta.naver.com, api.hanju.koudaibaobao.com
