#!name=湖南卫视
#!desc=某些APP要清除缓存或者重新安装拦截广告才会生效！
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Rule]
DOMAIN-SUFFIX,da.hunantv.com,REJECT
DOMAIN-SUFFIX,log.hunantv.com,REJECT
DOMAIN-SUFFIX,v2.hunantv.com,REJECT
DOMAIN-SUFFIX,click.hunantv.com,REJECT
DOMAIN-SUFFIX,mp4.res.hunantv.com,REJECT
DOMAIN-SUFFIX,res.hunantv.com,REJECT
DOMAIN-SUFFIX,x.da.hunantv.com,REJECT
DOMAIN-SUFFIX,x1.da.hunantv.com,REJECT
DOMAIN-SUFFIX,y.da.hunantv.com,REJECT
DOMAIN-SUFFIX,log.v2.hunantv.com,REJECT
DOMAIN-SUFFIX,v2.log.hunantv.com,REJECT
