#!name=虎牙直播
#!desc=某些APP要清除缓存或者重新安装拦截广告才会生效！
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Rule]
DOMAIN,pp-cdnfile2pcdn.msstatic.com,REJECT
DOMAIN,livewebbs2pcdn.msstatic.com,REJECT
DOMAIN,huyafile.msstatic.com,REJECT
DOMAIN,livewebbs2.msstatic.com,REJECT
DOMAIN,business.msstatic.com,REJECT
DOMAIN-SUFFIX,v1d.szbdyd.com,REJECT
DOMAIN-SUFFIX,3dm.huya.com,REJECT

[URL Rewrite]
^https?:\/\/cdn\.wup\.huya\.com\/launch\/queryHttpDns$ - reject
^https?:\/\/business\.msstatic\.com\/advertiser\/material - reject

[Map Local]
^https?:\/\/cdnfile1\.msstatic\.com\/cdnfile\/appad\/ data-type=tiny-gif status-code=200
^https?://live-ads\.huya\.com/live/getAllEntrance.*$ data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[MITM]
hostname = %APPEND% cdn.wup.huya.com, business.msstatic.com, cdnfile1.msstatic.com, live-ads.huya.com
