#!name=驾考宝典
#!desc=某些APP要清除缓存或者重新安装拦截广告才会生效！
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[URL Rewrite]
^https?:\/\/\w+\.kakamobi\.cn\/api\/open\/v\d\/advert-sdk\/ - reject

[Map Local]
^https?:\/\/789\.kakamobi\.cn\/.+adver data-type=tiny-gif status-code=200
^https?:\/\/smart\.789\.image\.mucang\.cn\/advert data-type=tiny-gif status-code=200

[MITM]
hostname = %APPEND% *.kakamobi.cn, smart.789.image.mucang.cn
