#!name=驾校一点通
#!desc=某些APP要清除缓存或者重新安装拦截广告才会生效！
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Rule]
DOMAIN,richmanapi.jxedt.com,REJECT
DOMAIN,richmanmain.jxedt.com,REJECT
DOMAIN,richmanrules.jxedt.com,REJECT

[URL Rewrite]
^https?:\/\/richmanrules\.ksedt\.com\/intellectWaterfall(Bidding)?\/find - reject
^https?:\/\/api\.jxedt\.com\/ad\/ - reject

[Map Local]
^https?:\/\/richmanapi\.jxedt\.com\/api\/(ad|adplus|banadplus)\/ data-type=text data=" " status-code=200
^https?:\/\/api\.jxedt\.com\/jump\/EMiCcDNp data-type=tiny-gif status-code=200
^https?:\/\/richmanmain\.jxedt\.com\/advertisement\/fallback data-type=tiny-gif status-code=200

[MITM]
hostname = %APPEND% richmanrules.ksedt.com, api.jxedt.com, richmanapi.jxedt.com
