#!name=Keep
#!desc=某些APP要清除缓存或者重新安装拦截广告才会生效！
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Rule]
DOMAIN,httpdns.n.netease.com,REJECT
DOMAIN,httpdns.calorietech.com,REJECT
DOMAIN,hc-ssp.sm.cn,REJECT
DOMAIN,apm.gotokeep.com,REJECT
DOMAIN,kad.gotokeep.com,REJECT

[URL Rewrite]
^https?:\/\/api\.gotokeep\.com\/guide-webapp\/v\d\/popup\/getPopUp - reject
^https?:\/\/api\.gotokeep\.com\/kprime\/v\d\/popups\/primeGuide - reject
^https?:\/\/kad\.gotokeep\.com\/op-engine-webapp\/v\d\/ad - reject
^https?:\/\/api.gotokeep.com/cauchy/growth/init - reject
^https?:\/\/api\.gotokeep\.com\/search\/v\d\/default\/keyword\/list - reject
^https?:\/\/api\.gotokeep\.com\/search\/v\d\/hotword\/list - reject
^https?:\/\/api\.gotokeep\.com\/search\/v\d\/hotCourse\/list - reject
^https?:\/\/api\.gotokeep\.com\/op-engine-webapp\/v\d\/ad - reject
^https?:\/\/api\.gotokeep\.com\/ads\/v\d\/ads\/preload - reject
^https?:\/\/api\.gotokeep\.com\/training\/box\/config - reject
^https?:\/\/api\.gotokeep\.com\/anno\/v\d\/upgrade\/check - reject

[Map Local]
^https?:\/\/static1\.keepcdn\.com\/ark_optimus\/202\d\/*\/*\/.*.(png|jpg) data-type=text data=" " status-code=200

[Script]
keep = type=http-response, pattern=^https?:\/\/api\.gotokeep\.com\/athena\/v\d\/people\/my$, script-path=https://raw.githubusercontent.com/fmz200/wool_scripts/main/Scripts/keep.js, requires-body=true, timeout=60
keep = type=http-response, pattern=^https?:\/\/api\.gotokeep\.com\/config\/v\d\/basic, script-path=https://raw.githubusercontent.com/fmz200/wool_scripts/main/Scripts/keep.js, requires-body=true, timeout=60
keep = type=http-response, pattern=^https?:\/\/api\.gotokeep\.com\/homepage\/v\d\/tab, script-path=https://raw.githubusercontent.com/fmz200/wool_scripts/main/Scripts/keep.js, requires-body=true, timeout=60
keep = type=http-response, pattern=^https?:\/\/api\.gotokeep\.com\/nuocha\/course\/v\d/\w+\/preview, script-path=https://raw.githubusercontent.com/fmz200/wool_scripts/main/Scripts/keep.js, requires-body=true, timeout=60
keep = type=http-response, pattern=^https?:\/\/api\.gotokeep\.com\/sportpage\/sport\/v\d\/mysport, script-path=https://raw.githubusercontent.com/fmz200/wool_scripts/main/Scripts/keep.js, requires-body=true, timeout=60

[MITM]
hostname = %APPEND% api.gotokeep.com, kad.gotokeep.com, static1.keepcdn.com
