#!name=快乐广播
#!desc=某些APP要清除缓存或者重新安装拦截广告才会生效！
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Rule]
DOMAIN,ad.hpplay.cn,REJECT
DOMAIN,adc.hpplay.cn,REJECT
DOMAIN,adcdn.hpplay.cn,REJECT
DOMAIN,adeng.hpplay.cn,REJECT
DOMAIN,pin.hpplay.cn,REJECT
DOMAIN,rp.hpplay.cn,REJECT
DOMAIN,rpt.hpplay.cn,REJECT
DOMAIN-SUFFIX,e.kuaishou.com,REJECT
DOMAIN-SUFFIX,cm.downloader.commercial.kuaishou.com,REJECT
DOMAIN-SUFFIX,cm.ad.gifshow.com,REJECT
DOMAIN-SUFFIX,cm.kwad.com,REJECT
