#!name=懒人听书
#!desc=某些APP要清除缓存或者重新安装拦截广告才会生效！
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[URL Rewrite]
^https?:\/\/.*\/yyting\/advertclient\/ClientAdvertList.action - reject

[Map Local]
^https?:\/\/118\.178\.214\.118\/yyting\/advertclient\/ClientAdvertList\.action data-type=tiny-gif status-code=200
^https?:\/\/dapis\.mting\.info\/yyting\/advertclient\/ClientAdvertList\.action data-type=tiny-gif status-code=200
^https?:\/\/display\.wting\.info\/.*.jpeg data-type=text data=" " status-code=200

[MITM]
hostname = %APPEND% 118.178.214.118, dapis.mting.info, display.wting.info
