#!name=lofter
#!desc=某些APP要清除缓存或者重新安装拦截广告才会生效！
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Map Local]
^https?:\/\/ad\.lofter.com\/v1\.1\/yitou\/madr data-type=text data=" " status-code=200
^https?:\/\/images\.pinduoduo\.com\/marketing\_api data-type=text data=" " status-code=200
^https?:\/\/lofter\.lf127\.net\/ad\-material data-type=text data=" " status-code=200

[MITM]
hostname = %APPEND% ad.lofter.com, images.pinduoduo.com, lofter.lf127.net
