#!name=马蜂窝
#!desc=某些APP要清除缓存或者重新安装拦截广告才会生效！
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[URL Rewrite]
^https?:\/\/mapi\.mafengwo\.cn\/(travelguide\/)?ad - reject
^https?:\/\/mapi\.mafengwo\.cn\/widget\/note\/get_widget_note - reject
^https?:\/\/mapi\.mafengwo\.cn\/system\/push\/get_local_push_config - reject

[Map Local]
^https?:\/\/mapi\.mafengwo\.cn\/system\/update\/check_update data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https?:\/\/mapi\.mafengwo\.cn\/system\/config\/(get|mark)_(push|alert)_config data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[Script]
马蜂窝 = type=http-response, pattern=^https?:\/\/mapi\.mafengwo\.cn\/user\/profile\/get_(list|profile), script-path=https://raw.githubusercontent.com/zirawell/R-Store/main/Res/Scripts/AntiAd/mafengwo.js, requires-body=true, timeout=60

[MITM]
hostname = %APPEND% mapi.mafengwo.cn
