#!name=漫画人
#!desc=某些APP要清除缓存或者重新安装拦截广告才会生效！
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[URL Rewrite]
^https?:\/\/mangaapi\.manhuaren\.com\/v\d\/public\/getStartPageAds - reject
^https?:\/\/.*mangaapi\.manhuaren\.\w{2,4}\/v\d\/public\/(getStartUpMessage|getStartPageAds|getShelfActivity) - reject
^https?:\/\/.*mangaapi\.manhuaren\.\w{2,4}\/v\d\/ad - reject

[MITM]
hostname = %APPEND% mangaapi.manhuaren.com, *mangaapi.manhuaren.*
