#!name=美团
#!desc=某些APP要清除缓存或者重新安装拦截广告才会生效！
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Rule]
DOMAIN-SUFFIX,meituan.xn,REJECT
DOMAIN-SUFFIX,meituan.yoga,REJECT
DOMAIN-SUFFIX,meituangov.cn,REJECT
DOMAIN-SUFFIX,report.meituan.com,REJECT
DOMAIN-SUFFIX,analytics.meituan.net,REJECT
DOMAIN-SUFFIX,wmlog.meituan.com,REJECT
DOMAIN-SUFFIX,ad.e.waimai.sankuai.com,REJECT
DOMAIN-SUFFIX,mads.meituan.com,REJECT
DOMAIN-SUFFIX,dreport.meituan.net,REJECT
DOMAIN-SUFFIX,d.meituan.net,REJECT
