#!name=网易大神
#!desc=某些APP要清除缓存或者重新安装拦截广告才会生效！
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Rule]
DOMAIN,httpdns.music.163.com,REJECT
DOMAIN,httpdns.n.netease.com,REJECT
DOMAIN,httpdns-sdk.n.netease.com,REJECT
DOMAIN,httpdns.yunxindns.com,REJECT
DOMAIN,lofter.httpdns.c.163.com,REJECT
DOMAIN,music.httpdns.c.163.com,REJECT
IP-CIDR,59.111.239.61/32,REJECT,no-resolve
IP-CIDR,59.111.239.62/32,REJECT,no-resolve
IP-CIDR,115.236.121.51/32,REJECT,no-resolve
IP-CIDR,115.236.121.195/32,REJECT,no-resolve

[URL Rewrite]
^https:\/\/god\.gameyw\.netease\.com\/v\d\/ad - reject

[Body Rewrite]
http-response-jq ^https:\/\/app-conf\.ds\.163\.com\/v\d\/app\/base\/conf\/static\/start-config\? 'delpaths([["result","updateConfig",2,"itemList",94,"itemList",2]])'

[Map Local]
^https:\/\/god\.gameyw\.netease\.com\/v\d\/app\/static\/conf\/getByModuleNameList$ data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[MITM]
hostname = %APPEND% god.gameyw.netease.com, app-conf.ds.163.com
