#!name=ONE
#!desc=某些APP要清除缓存或者重新安装拦截广告才会生效！
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[URL Rewrite]
^https?:\/\/app\.api\.d3yuiw4\.com\/api\/app\/ad - reject
^https?:\/\/api\.21ec74\.com\/v2\.5\/ad - reject

[Map Local]
^https?:\/\/v3\.wufazhuce\.com:8000\/api\/adpreloadlist data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[MITM]
hostname = %APPEND% v3.wufazhuce.com, app.api.d3yuiw4.com, api.21ec74.com
