#!name=人民日报
#!desc=某些APP要清除缓存或者重新安装拦截广告才会生效！
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[URL Rewrite]
^https?:\/\/app\.peopleapp\.com\/Api\/\d+/HomeApi\/(adv|getAdvertImage) - reject
^https?:\/\/stat\.peopleapp\.com\/ - reject

[Map Local]
^https?:\/\/adstatic\.peopleapp\.com\/upload\/AppLoad\/.*.(jpg|png) data-type=text data=" " status-code=200

[MITM]
hostname = %APPEND% app.peopleapp.com, stat.peopleapp.com, adstatic.peopleapp.com
