#!name=起点读书
#!desc=某些APP要清除缓存或者重新安装拦截广告才会生效！
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[URL Rewrite]
^https?:\/\/mage\.if\.qidian\.com\/argus\/api\/v\d\/client\/getsplashscreen - reject
^https?://magev6.if.qidian.com/argus/api/v1/client/iosad - reject
^https?://magev6.if.qidian.com/argus/api/v1/bookshelf/getad - reject
^https?://magev6.if.qidian.com/argus/api/v4/client/getsplashscreen? - reject
^https?:\/\/magev6\.if\.qidian\.com\/argus\/api\/v1\/adv\/getadvlistbatch - reject

[Map Local]
^https?:\/\/qidian\.qpic\.cn\/qidian_common data-type=tiny-gif status-code=200
^https?:\/\/mage\.if\.qidian\.com\/Atom\.axd\/Api\/Client\/GetConfIOS data-type=tiny-gif status-code=200
^https?:\/\/magev6\.if\.qidian\.com\/argus\/api\/v1\/adv data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https?:\/\/magev6\.if\.qidian\.com\/argus\/api\/v1\/followsubscribe data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^http[s]?:\/\/magev6\.if\.qidian\.com\/argus\/api\/v1\/bookshelf\/refresh data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https?:\/\/magev6\.if\.qidian\.com\/argus\/api\/v1\/bookshelf\/getTopOperation data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https?:\/\/magev6\.if\.qidian\.com\/argus\/api\/v2\/adv\/getadvlistbatch data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[MITM]
hostname = %APPEND% qidian.qpic.cn, mage.if.qidian.com, magev6.if.qidian.com
