#!name=去哪儿
#!desc=某些APP要清除缓存或者重新安装拦截广告才会生效！
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[URL Rewrite]
^https?:\/\/client\.qunar\.com\/pitcher-proxy\?qrt=p_splashAd - reject

[Map Local]
^https?:\/\/qde\.qunar\.com\/preload data-type=text data=" " status-code=200
^https?:\/\/homefront\.qunar\.com\/front\/splash\/ad data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[MITM]
hostname = %APPEND% qde.qunar.com, homefront.qunar.com, client.qunar.com
