#!name=Tanwan (贪玩)
#!desc=某些APP要清除缓存或者重新安装拦截广告才会生效！
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Rule]
DOMAIN-SUFFIX,mytanwan.com,REJECT
DOMAIN-SUFFIX,tanwanyx.com,REJECT
DOMAIN-SUFFIX,app.tanwan.com,REJECT
DOMAIN-SUFFIX,wap.tanwan.com,REJECT
DOMAIN-SUFFIX,gafxa.code.mytanwan.com,REJECT
DOMAIN-SUFFIX,ldpgl.code.mytanwan.com,REJECT
DOMAIN-SUFFIX,pop.code.mytanwan.com,REJECT
DOMAIN-SUFFIX,sy.code.mytanwan.com,REJECT
DOMAIN-SUFFIX,sy.flash.mytanwan.com,REJECT
DOMAIN-SUFFIX,b.code.tanwanyx.com,REJECT
DOMAIN-SUFFIX,hv.code.tanwanyx.com,REJECT
DOMAIN-SUFFIX,xd.code.tanwanyx.com,REJECT
