#!name=澎湃新闻
#!desc=某些APP要清除缓存或者重新安装拦截广告才会生效！
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Rule]
DOMAIN,admonitor.thepaper.cn,REJECT
DOMAIN,adpai.thepaper.cn,REJECT
DOMAIN,imgadpai.thepaper.cn,REJECT
DOMAIN-SUFFIX,ad.thepaper.cn,REJECT
DOMAIN-SUFFIX,imgad.thepaper.cn,REJECT

[URL Rewrite]
^https?:\/\/adpai\.thepaper\.cn\/.+&ad= - reject

[MITM]
hostname = %APPEND% adpai.thepaper.cn
