#!name=TubeMax
#!desc=某些APP要清除缓存或者重新安装拦截广告才会生效！
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Rule]
DOMAIN-SUFFIX,adjust.com,REJECT
DOMAIN-SUFFIX,applvn.com,REJECT
DOMAIN-SUFFIX,app-measurement.com,REJECT
DOMAIN-SUFFIX,pangle.io,REJECT
DOMAIN-SUFFIX,applovin.com,REJECT
DOMAIN-SUFFIX,appier.net,REJECT
DOMAIN-SUFFIX,adsmoloco.com,REJECT
DOMAIN-SUFFIX,adcanvas.com,REJECT

[URL Rewrite]
^https?:\/\/.*\.i18n-pglstatp\.com\/obj\/ad-pattern-sg - reject

[MITM]
hostname = %APPEND% *.i18n-pglstatp.com
