#!name=WiFi万能钥匙
#!desc=某些APP要清除缓存或者重新安装拦截广告才会生效！
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Rule]
DOMAIN-KEYWORD,app.51y5.net,REJECT
DOMAIN-KEYWORD,apiinit.amap.com,REJECT
DOMAIN-KEYWORD,c.51y5.net,REJECT
DOMAIN-KEYWORD,msg.push.51y5.net,REJECT
DOMAIN-KEYWORD,a.wkanx.com,REJECT
DOMAIN-KEYWORD,c.wkanx.com,REJECT
DOMAIN-KEYWORD,c1.wkanx.com,REJECT
DOMAIN-KEYWORD,ap.51y5.net,REJECT
DOMAIN-KEYWORD,dc.51y5.net,REJECT
DOMAIN-KEYWORD,push-dc.51y5.net,REJECT
DOMAIN-KEYWORD,news-log.51y5.net,REJECT
DOMAIN-KEYWORD,login.push.51y5.net,REJECT
DOMAIN-KEYWORD,news.51y5.net,REJECT
DOMAIN-KEYWORD,cds.51y5.net,REJECT
DOMAIN-KEYWORD,insurance.lianwifi.com,REJECT
DOMAIN-KEYWORD,config.51y5.net,REJECT
DOMAIN-KEYWORD,static.wkanx.com,REJECT
DOMAIN-KEYWORD,config.y5en.com,REJECT
DOMAIN-SUFFIX,mi.gdt.qq.com,REJECT
DOMAIN,taichi.51y5.net,REJECT

[Map Local]
^https?:\/\/cds\.wifi188\.com\/feeds\.sec data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[MITM]
hostname = %APPEND% cds.wifi188.com
