#!name=下厨房
#!desc=某些APP要清除缓存或者重新安装拦截广告才会生效！
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[URL Rewrite]
^https?:\/\/api\.xiachufang\.com\/v\d\/ad/ - reject

[Map Local]
^https?:\/\/images\.cib\.com\.cn\/commons\/uploads\/commons\/[a-zA-Z0-9]{32}\.jpg\?ver=20221[1-2]{1} data-type=text data=" " status-code=200
^https?:\/\/images\.cib\.com\.cn\/commons\/uploads\/commons\/[a-zA-Z0-9]{32}\.jpg\?ver=20230[1-9]{1} data-type=text data=" " status-code=200
^http?:\/\/.*\.pglstatp-toutiao\.com data-type=text data=" " status-code=200
^http:\/\/res1\.hubcloud\.com\.cn data-type=text data=" " status-code=200

[MITM]
hostname = %APPEND% *.pglstatp-toutiao.com, res1.hubcloud.com.cnhostname
