#!name=小桔科技
#!desc=某些APP要清除缓存或者重新安装拦截广告才会生效！
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[URL Rewrite]
^https?:\/\/ct\.xiaojukeji\.com\/agent\/v3\/feeds - reject
^https?:\/\/res\.xiaojukeji\.com\/resapi\/activity\/get(Ruled|Preload|PasMultiNotices) - reject
^https?:\/\/res\.xiaojukeji\.com\/resapi\/activity\/mget - reject

[MITM]
hostname = %APPEND% ct.xiaojukeji.com, res.xiaojukeji.com
