#!name=易车
#!desc=某些APP要清除缓存或者重新安装拦截广告才会生效！
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Rule]
DOMAIN,adx.yiche.com,REJECT
DOMAIN,log.ycapp.yiche.com,REJECT
DOMAIN-SUFFIX,bglog.bitauto.com,REJECT
DOMAIN-SUFFIX,g.bitauto.com,REJECT
DOMAIN-SUFFIX,gimg.bitauto.com,REJECT
DOMAIN-SUFFIX,gstat.bitauto.com,REJECT

[Map Local]
^https?:\/\/api\.ycapp\.yiche\.com\/appnews\/getadlist data-type=tiny-gif status-code=200
^https?:\/\/api\.ycapp\.yiche\.com\/yicheapp\/getadlist data-type=tiny-gif status-code=200
^https?:\/\/cheyouapi\.ycapp\.yiche\.com\/appforum\/getusermessagecount data-type=tiny-gif status-code=200

[MITM]
hostname = %APPEND% api.ycapp.yiche.com, cheyouapi.ycapp.yiche.com
