#!name=医考帮
#!desc=某些APP要清除缓存或者重新安装拦截广告才会生效！
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[URL Rewrite]
^https?:\/\/api\.yikaobang\.com\.cn\/client\/main\/homePageSmallAd - reject
^https?:\/\/api\.yikaobang\.com\.cn\/index\.php\/Client\/main\/startPage - reject
^https?:\/\/api\.yikaobang\.com\.cn\/index\.php\/version\/version\/check - reject

[MITM]
hostname = %APPEND% api.yikaobang.com.cn
