#!name=有米
#!desc=某些APP要清除缓存或者重新安装拦截广告才会生效！
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Rule]
DOMAIN-SUFFIX,wumii.cn,REJECT
DOMAIN-SUFFIX,wumii.com,REJECT
DOMAIN-SUFFIX,app.wumii.com,REJECT
DOMAIN-SUFFIX,youmi.net,REJECT
DOMAIN-SUFFIX,au.youmi.net,REJECT
DOMAIN-SUFFIX,notifiter.youmi.net,REJECT
DOMAIN-SUFFIX,r.youmi.net,REJECT
DOMAIN-SUFFIX,s.youmi.net,REJECT
DOMAIN-SUFFIX,t.youmi.net,REJECT
DOMAIN-SUFFIX,aos.wall.youmi.net,REJECT
