#!name=掌上英雄联盟
#!desc=某些APP要清除缓存或者重新安装拦截广告才会生效！
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[URL Rewrite]
^https?:\/\/mlol\.qt\.qq\.com\/go\/recommend - reject

[Map Local]
^https?:\/\/us\.l\.qq\.com\/exapp data-type=text data=" " status-code=200
^https?:\/\/ossweb-img\.qq\.com\/upload\/adw\/image\/[0-9]{3}\/202[0-9]{5}\/[a-z0-9]{32}\.(jpg|jpeg) data-type=text data=" " status-code=200

[MITM]
hostname = %APPEND% us.l.qq.com, ossweb-img.qq.com, mlol.qt.qq.com
