#!name=中华万年历
#!desc=某些APP要清除缓存或者重新安装拦截广告才会生效！
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Rule]
DOMAIN-KEYWORD,lkme.cc,REJECT
DOMAIN-KEYWORD,api.freed.so,REJECT
DOMAIN-KEYWORD,log-dmp.suishenyun.cn,REJECT
DOMAIN-KEYWORD,client-dmp.suishenyun.cn,REJECT
DOMAIN-KEYWORD,pc.suishenyun.net,REJECT
DOMAIN-KEYWORD,v0-client-lz.rili.cn,REJECT
DOMAIN-SUFFIX,ad.51wnl.com,REJECT
DOMAIN-SUFFIX,ad-android.51wnl.com,REJECT
DOMAIN-SUFFIX,ad.51wnl-cq.com,REJECT
DOMAIN-SUFFIX,adextra.51wnl-cq.com,REJECT
