dns:
  bootstrap: # DNS 引导器：用于解析上游DNS(DoT、DoH、DoQ)，默认 system
  - system

  upstreams: # 上游 DNS 服务器
    ChinaDNS: # 国内公共加密 DNS
    - https://223.5.5.5
    GlobalDNS: # 国外公共加密 DNS (不推荐，自行启用)
    - https://8.8.8.8

  forward: # 转发规则

  # 阿里
  - wildcard: # 阿里巴巴
      match: '*.alibaba.cn'
      value: ChinaDNS
  - wildcard: # 阿里巴巴
      match: '*.alibaba.com.cn'
      value: ChinaDNS
  - wildcard: # Alibaba 中国
      match: '*.china.alibaba.com'
      value: ChinaDNS
  - wildcard: # 1688
      match: '*.1688.com'
      value: ChinaDNS
  - wildcard: # 淘宝
      match: '*.taobao.com'
      value: ChinaDNS
  - wildcard: # 淘宝 缓存
      match: '*.tbcache.com'
      value: ChinaDNS
  - wildcard: # 天猫
      match: '*.tmall.com'
      value: ChinaDNS
  - wildcard: # 阿里 CDN
      match: '*.alicdn.com'
      value: ChinaDNS
  - wildcard: # 阿里昆仑
      match: '*.alikunlun.com'
      value: ChinaDNS
  - wildcard: # 云引擎应用平台
      match: '*.aliapp.com'
      value: ChinaDNS
  - wildcard: # 上云平台
      match: '*.aliapp.org'
      value: ChinaDNS
  - wildcard: # 阿里用户上传资料
      match: '*.alibabausercontent.com'
      value: ChinaDNS
  - wildcard: # mmstat 数据统计 广告追踪
      match: '*.mmstat.com'
      value: ChinaDNS
  - wildcard: # 淘宝短网址
      match: 'tb.cn'
      value: ChinaDNS
  - wildcard: # 阿里云
      match: '*.aliyun.*'
      value: ChinaDNS
  - wildcard: # 阿里云 CDN
      match: '*.aliyuncdn.*'
      value: ChinaDNS
  - wildcard: # 阿里云 API 服务
      match: '*.aliyuncs.com'
      value: ChinaDNS
  - wildcard: # 阿里云 DDoS防护
      match: '*.aliyunddos.com'
      value: ChinaDNS
  - wildcard: # 阿里云盘
      match: '*.aliyundrive.com'
      value: ChinaDNS
  - wildcard: # 阿里云盾
      match: '*.aliyundun.com'
      value: ChinaDNS
  - wildcard: # 阿里云盾 Web 应用防火墙
      match: '*.aliyundunwaf.com'
      value: ChinaDNS
  - wildcard: # 阿里云 内部
      match: '*.aliyun-inc.com'
      value: ChinaDNS

  # 蚂蚁集团
  - wildcard: # 蚂蚁集团
      match: '*.antgroup.com'
      value: ChinaDNS
  - wildcard: # 蚂蚁金服
      match: '*.antfin.com'
      value: ChinaDNS
  - wildcard: # 蚂蚁金服
      match: '*.antfinancial.com'
      value: ChinaDNS
  - wildcard: # 支付宝
      match: '*.alipay.com'
      value: ChinaDNS
  - wildcard: # 支付宝
      match: '*.alipay.com.cn'
      value: ChinaDNS
  - wildcard: # 支付宝 HTTP DNS
      match: '*.alipaydns.com'
      value: ChinaDNS
  - wildcard: # 支付宝 商家资源
      match: '*.alipayeshop.com'
      value: ChinaDNS
  - wildcard: # 支付宝 Mdap
      match: '*.alipaylog.com'
      value: ChinaDNS
  - wildcard: # 支付宝 静态资源
      match: '*.alipayobjects.com'
      value: ChinaDNS
  - wildcard: # 支付宝 开放技术生态体系
      match: '*.alipay-eco.com'
      value: ChinaDNS

  # 腾讯
  - wildcard: # 腾讯
      match: '*.tencent.com'
      value: ChinaDNS
  - wildcard: # 腾讯云
      match: '*.qcloud.com'
      value: ChinaDNS
  - wildcard: # 腾讯云CDN
      match: '*.qcloudcdn.cn'
      value: ChinaDNS
  - wildcard: # 腾讯云CDN
      match: '*.qcloudcdn.com'
      value: ChinaDNS
  - wildcard: # 腾讯云对象储存
      match: '*.qcloudcos.com'
      value: ChinaDNS
  - wildcard: # 腾讯云静态资源
      match: '*.qcloudimg.com'
      value: ChinaDNS
  - wildcard: # 腾讯云超级管家
      match: '*.qcloudcjgj.com'
      value: ChinaDNS
  - wildcard: # 腾讯云网站管家
      match: '*.qcloudwzgj.com'
      value: ChinaDNS
  - wildcard: # 腾讯云主页管家
      match: '*.qcloudzygj.com'
      value: ChinaDNS
  - wildcard: # 腾讯开放云
      match: '*.myqcloud.com'
      value: ChinaDNS
  - wildcard: # 腾讯云
      match: '*.tencent-cloud.net'
      value: ChinaDNS
  - wildcard: # 腾讯云aiot解决方案
      match: '*.tencentcloud-aiot.com'
      value: ChinaDNS
  - wildcard: # 腾讯云API
      match: '*.tencentcloudapi.com'
      value: ChinaDNS
  - wildcard: # 腾讯云容器镜像服务TCR
      match: '*.tencentcloudcr.com'
      value: ChinaDNS
  - wildcard: # 腾讯云云市场
      match: '*.tencentcloudmarket.com'
      value: ChinaDNS
  - wildcard: # QQ
      match: '*.qq.com'
      value: ChinaDNS
  - wildcard: # 腾讯头像
      match: '*.qlogo.cn'
      value: ChinaDNS
  - wildcard: # 腾讯图片
      match: '*.qpic.cn'
      value: ChinaDNS
  - wildcard: # 微信
      match: '*.weixin.qq.com'
      value: ChinaDNS
  - wildcard: # 微信
      match: '*.wx.qq.com'
      value: ChinaDNS
  - wildcard: # 微信
      match: '*.weixin.com'
      value: ChinaDNS
  - wildcard: # 微信公众平台
      match: '*.weixinbridge.com'
      value: ChinaDNS
  - wildcard: # WeChat
      match: '*.wechat.com'
      value: ChinaDNS
  - wildcard: # 微信小程序
      match: '*.servicewechat.com'
      value: ChinaDNS
  - wildcard: # 微云
      match: '*.weiyun.com'
      value: ChinaDNS
  - wildcard: # 腾讯 图片 静态资源
      match: '*.gtimg.cn'
      value: ChinaDNS
  - wildcard: # 腾讯 图片 静态资源
      match: '*.idqqimg.com'
      value: ChinaDNS
  - wildcard: # 腾讯 静态资源 CDN
      match: '*.cdn-go.cn'
      value: ChinaDNS
  - wildcard: # 腾讯云 智能云解析DNS
      match: '*.smtcdns.com'
      value: ChinaDNS
  - wildcard: # 腾讯云 智能云解析DNS
      match: '*.smtcdns.net'
      value: ChinaDNS
  - wildcard: # 腾讯短网址
      match: 'url.cn'
      value: ChinaDNS

  # 百度
  - wildcard: # 百度
      match: '*.baidu'
      value: ChinaDNS
  - wildcard: # 百度
      match: '*.baidu.com'
      value: ChinaDNS
  - wildcard: # 百度 静态资源
      match: '*.bdimg.com'
      value: ChinaDNS
  - wildcard: # 百度 静态资源
      match: '*.bdstatic.com'
      value: ChinaDNS
  - wildcard: # 百度网盘
      match: '*.baidupcs.*'
      value: ChinaDNS
  - wildcard: # 百度云CDN
      match: '*.baiduyuncdn.*'
      value: ChinaDNS
  - wildcard: # 百度云DNS
      match: '*.baiduyundns.*'
      value: ChinaDNS
  - wildcard: # 百度云 DNS
      match: '*.bdydns.*'
      value: ChinaDNS
  - wildcard: # 百度云 CDN
      match: '*.bdycdn.*'
      value: ChinaDNS
  - wildcard: # 百度云 域名
      match: '*.bdysite.com'
      value: ChinaDNS
  - wildcard: # 百度云 域名
      match: '*.bdysites.com'
      value: ChinaDNS
  - wildcard: # 百度智能云
      match: '*.baidubce.*'
      value: ChinaDNS
  - wildcard: # 百度智能云 DNS
      match: '*.bcedns.*'
      value: ChinaDNS
  - wildcard: # 百度智能云 对象存储BOS
      match: '*.bcebos.com'
      value: ChinaDNS
  - wildcard: # 百度智能云 播放器服务
      match: '*.bcevod.com'
      value: ChinaDNS
  - wildcard: # 百度智能云 图片服务
      match: '*.bceimg.com'
      value: ChinaDNS
  - wildcard: # 百度智能云 主机
      match: '*.bcehost.com'
      value: ChinaDNS
  - wildcard: # 百度智能云 主机
      match: '*.bcehosts.com'
      value: ChinaDNS
  - wildcard: # 百度短网址
      match: 'dwz.cn'
      value: ChinaDNS

  # 360
  - wildcard: # 360安全中心
      match: '*.360.cn'
      value: ChinaDNS
  - wildcard: # 360安全卫士
      match: '*.360safe.com'
      value: ChinaDNS
  - wildcard: # 360快资讯
      match: '*.360kuai.com'
      value: ChinaDNS
  - wildcard: # 360搜索
      match: '*.so.com'
      value: ChinaDNS
  - wildcard: # 360网页快照服务
      match: '*.360webcache.com'
      value: ChinaDNS
  - wildcard: # 奇虎api
      match: '*.qihuapi.com'
      value: ChinaDNS
  - wildcard: # 360图床
      match: '*.qhimg.com'
      value: ChinaDNS
  - wildcard: # 360图床
      match: '*.qhimgs.com'
      value: ChinaDNS
  - wildcard: # 360图床
      match: '*.qhimgs?.com'
      value: ChinaDNS
  - wildcard: # 360
      match: '*.qhmsg.com'
      value: ChinaDNS
  - wildcard: # 奇虎静态资源
      match: '*.qhres.com'
      value: ChinaDNS
  - wildcard: # 奇虎静态资源
      match: '*.qhres?.com'
      value: ChinaDNS
  - wildcard: # 导航静态文件
      match: '*.dhrest.com'
      value: ChinaDNS
  - wildcard: # 360
      match: '*.qhupdate.com'
      value: ChinaDNS
  - wildcard: # 360安全云盘
      match: '*.yunpan.cn'
      value: ChinaDNS
  - wildcard: # 360安全云盘
      match: '*.yunpan.com.cn'
      value: ChinaDNS
  - wildcard: # 360安全云盘
      match: '*.yunpan.com'
      value: ChinaDNS
  - wildcard: # 360短网址
      match: 'urlqh.cn'
      value: ChinaDNS

  # Bytedance
  - wildcard: # 艾特迷
      match: '*.amemv.com'
      value: ChinaDNS
  - wildcard: # 西瓜 图片服务
      match: '*.bdxiguaimg.com'
      value: ChinaDNS
  - wildcard: # 西瓜 静态资源
      match: '*.bdxiguastatic.com'
      value: ChinaDNS
  - wildcard: # 字节跳动 UNPKG
      match: '*.byted-static.com'
      value: ChinaDNS
  - wildcard: # 字节跳动
      match: '*.bytedance.*'
      value: ChinaDNS
  - wildcard: # 字节跳动 DNS
      match: '*.bytedns.net'
      value: ChinaDNS
  - wildcard: # 字节跳动 CDN 文件存储
      match: '*.bytednsdoc.com'
      value: ChinaDNS
  - wildcard: # 字节跳动 Goofy
      match: '*.bytegoofy.com'
      value: ChinaDNS
  - wildcard: # 字节跳动 图片服务
      match: '*.byteimg.com'
      value: ChinaDNS
  - wildcard: # 字节跳动 SCM
      match: '*.bytescm.com'
      value: ChinaDNS
  - wildcard: # 字节跳动 TOS
      match: '*.bytetos.com'
      value: ChinaDNS
  - wildcard: # 飞书企业服务平台
      match: '*.bytexservice.com'
      value: ChinaDNS
  - wildcard: # 抖音
      match: '*.douyin.com'
      value: ChinaDNS
  - wildcard: # 抖音 静态资源
      match: '*.douyinpic.com'
      value: ChinaDNS
  - wildcard: # 抖音 静态资源
      match: '*.douyinstatic.com'
      value: ChinaDNS
  - wildcard: # 抖音 静态资源
      match: '*.douyinvod.com'
      value: ChinaDNS
  - wildcard: # FeelGood平台
      match: '*.feelgood.cn'
      value: ChinaDNS
  - wildcard: # 飞聊官网
      match: '*.feiliao.com'
      value: ChinaDNS
  - wildcard: # 快手
      match: '*.gifshow.com'
      value: ChinaDNS
  - wildcard: # 火山网
      match: '*.huoshan.com'
      value: ChinaDNS
  - wildcard: # 火山直播
      match: '*.huoshanzhibo.com'
      value: ChinaDNS
  - wildcard: # 抖音 dapm
      match: '*.ibytedapm.com'
      value: ChinaDNS
  - wildcard: # 抖音 CDN
      match: '*.iesdouyin.com'
      value: ChinaDNS
  - wildcard: # 西瓜视频
      match: '*.ixigua.com'
      value: ChinaDNS
  - wildcard: # 快手
      match: '*.kspkg.com'
      value: ChinaDNS
  - wildcard: # 抖音 静态资源
      match: '*.pstatp.com'
      value: ChinaDNS
  - wildcard: # 今日头条
      match: '*.snssdk.com'
      value: ChinaDNS
  - wildcard: # 今日头条
      match: '*.toutiao.com'
      value: ChinaDNS
  - wildcard: # 今日头条
      match: '*.toutiao13.com'
      value: ChinaDNS
  - wildcard: # 今日头条 静态资源
      match: '*.toutiao???.???'
      value: ChinaDNS
  - wildcard: # 头条云
      match: '*.toutiaocloud.cn'
      value: ChinaDNS
  - wildcard: # 头条云
      match: '*.toutiaocloud.com'
      value: ChinaDNS
  - wildcard: # 今日头条 建站
      match: '*.toutiaopage.com'
      value: ChinaDNS
  - wildcard: # 悟空
      match: '*.wukong.com'
      value: ChinaDNS
  - wildcard: # 字节跳动 API
      match: '*.zijieapi.com'
      value: ChinaDNS
  - wildcard: # 字节跳动 图片服务
      match: '*.zijieimg.com'
      value: ChinaDNS
  - wildcard: # 今日头条 网页版
      match: '*.zjbyte.com'
      value: ChinaDNS
  - wildcard: # 字节跳动 CDN
      match: '*.zjcdn.com'
      value: ChinaDNS

  # BiliBili
  - wildcard: # BiliBili upos视频服务器（阿里云）
      match: 'upos-sz-mirrorali.bilivideo.com'
      value: ChinaDNS
  - wildcard: # BiliBili upos视频服务器（阿里云）
      match: 'upos-sz-mirrorali?.bilivideo.com'
      value: ChinaDNS
  - wildcard: # BiliBili upos视频服务器（阿里云）
      match: 'upos-sz-mirrorali??.bilivideo.com'
      value: ChinaDNS
  - wildcard: # BiliBili upos视频服务器（百度云）
      match: 'upos-sz-mirrorbos.bilivideo.com'
      value: ChinaDNS
  - wildcard: # BiliBili upos视频服务器（腾讯云）
      match: 'upos-sz-mirrorcos.bilivideo.com'
      value: ChinaDNS
  - wildcard: # BiliBili upos视频服务器（腾讯云）
      match: 'upos-sz-mirrorcos?.bilivideo.com'
      value: ChinaDNS
  - wildcard: # BiliBili upos视频服务器（腾讯云）
      match: 'upos-sz-mirrorcos??.bilivideo.com'
      value: ChinaDNS
  - wildcard: # BiliBili upos视频服务器（百度云）
      match: 'upos-sz-upcdnbd??.bilivideo.com'
      value: ChinaDNS
  - wildcard: # BiliBili upos视频服务器（腾讯云）
      match: 'upos-sz-upcdntx.bilivideo.com'
      value: ChinaDNS

  - proxy_rule_set: # 国内域名规则集
      match: https://raw.githubusercontent.com/Auniquesir/Tool/X/Egern/Rules/China/China_All_No_Resolve.list
      value: system # 使用系统 DNS 解析
      update_interval: 86400
  - wildcard: # 通配符规则
      match: '*'
      value: GlobalDNS

  hosts: # 域名映射

    # > IPv6
    ip6-localhost: ::1 # IPv6 Localhost
    ip6-loopback: ::1 # IPv6 Loopback
    ip6-localnet: fe00::0 # IPv6 Link-Local
    ip6-mcastprefix: ff00::0 # IPv6 Multicast
    ip6-allnodes: ff02::1 # IPv6 All Nodes
    ip6-allrouters: ff02::2 # IPv6 All Routers
    ip6-allhosts: ff02::3 # IPv6 All Hosts

  public_ip_lookup_url: https://ifconfig.me/ip  # 公网 IP 地址查询
